- name: Configure the Palo Alto Networks firewall
  hosts: fw
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Include vars
    include_vars: 'vars.yml'
    no_log: 'yes'

  - name: "Configure eth1/1"
    panos_interface:
      provider: '{{ provider }}'
      if_name: 'ethernet1/1'
      zone_name: "L3-untrust"
      commit: False

  - name: "Configure eth1/2"
    panos_interface:
      provider: '{{ provider }}'
      if_name: 'ethernet1/2'
      zone_name: "L3-trust"
      commit: False

  - name: "Get all security rules"
    panos_security_rule_facts:
      provider: '{{ provider }}'
    register: rules

  - name: "Get all services"
    panos_object_facts:
      provider: '{{ provider }}'
      object_type: 'service'
      name_regex: '.*'
    register: srv

  - name: "Remove all the old security rules"
    panos_security_rule:
      provider: '{{ provider }}'
      rule_name: '{{ item }}'
      commit: False
    loop: '{{ rules.rules }}'
    loop_control:
      label: '{{ item }}'
    when:
      - item != "Deny everything else"

  - name: "Remove all old services"
    panos_service_object:
      provider: '{{ provider }}'
      state: 'absent'
      name: '{{ item.name }}'
      commit: False
    loop: '{{ srv.objects }}'
    loop_control:
      label: '{{ item.name }}'
