- name: Configure the Palo Alto Networks firewall
  hosts: fw
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Include vars
    include_vars: 'vars.yml'
    no_log: 'yes'

  - name: "Configure eth1/1"
    panos_interface:
      provider: '{{ provider }}'
      if_name: 'ethernet1/1'
      zone_name: "L3-untrust"
      commit: False

  - name: "Configure eth1/2"
    panos_interface:
      provider: '{{ provider }}'
      if_name: 'ethernet1/2'
      zone_name: "L3-trust"
      commit: False
